<input type="text" style="margin-top: 100px;" class="form-control" placeholder="Search.." >
<div class="row"style="margin-top: 50px; margin-bottom: 100px; padding-bottom 100px;">
    <?php
        $profile =new Profil();
        foreach($profiles as $profile){
    ?>
        <div class="card col-md-4" >
            <img class="card-img-top"
                src="data:image/jpg;base64,<?php echo $profile->getImageLien() ?>" alt="Card image" height="400px" width="250px" style="margin-top='100px';">
            <div class="card-body">
                <h4 class="card-title"><?php echo $profile->nom." ".$profile->prenom ?></h4>
                <p class="card-text"><?php echo $profile->description ?></p>
                <a href="#" class="btn btn-primary">See Profile</a>
            </div>
        </div>
<?php } ?>
</div>